apiVersion: v1
kind: Pod
metadata: 
  name: sample-web-a
  labels:
    app: sample-web-a
spec:
  containers:
  - name: sample-web-a
    image: kokiaptx0812/sample-web:case7
    env:
    - name: APP_NAME
      value: "Sample Web A"
    resources:
      requests:
        cpu: 1
      limits:
        cpu: 1